server:
  port: 3344


spring:
  rabbitmq:
    host: 192.168.165.129  #本机写localhost，服务器的写服务器地址
    port: 5672   #客户端和RabbitMQ进行通信的端口
    username: guest #默认也是guest
    password: guest #默认也是guest

  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/life4819/springcloud-config.git  #git的仓库地址
          search-paths: #搜索目录
            - springcloud-config
          username: 19986279225
          password: 784538304tsj.
          skip-ssl-validation: true
          strict-host-key-checking: false
      label: master   #读取的分支



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka   #服务注册到的eureka地址

#RabbitMQ相关配置
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'