server:
  port: 80


spring:
  application:
    name: cloud-order-service-feign
eureka:
  client:
    #true表示向注册中心注册自己，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/

#没提示不管它，可以设置
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接使用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

#开启日志的feign客户端
logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.lay.springcloud.service.PaymentFeignService: debug	#写你们自己的包名



feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 300000 # 5*60*1000
        loggerLevel: basic
    ap: localhost:8081
    dd: http://www.webxml.com.cn
